# use lightweight node as base image
FROM node:alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies (to be cached)
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# add rest of app
COPY . ./

# start app
CMD ["yarn", "start"]