version: '3'

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    links:
      - database
    depends_on:
      - database
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:3001
    environment:
      - DATABASE_URI=postgres://docker:docker@database:5432/docker

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - REACT_APP_API_URI=http://asking.one:8080
